DATASET_PATH = '/home/szamani/PycharmProjects/anomaly-detection/dataset/'
YAHOO_SUBPATH = 'A1Benchmark/'
YAHOO_BASE_FILENAME = 'real_{}.csv'
CONCEPTS_SUBPATH = 'concepts/'
POWER_PATH = 'powers/'
POWER_SUPPLY = 'power_supply.csv'
POWER_TRANSFORM = 'power_transform.csv'
LIGHT_PATH = 'sensor/light/'
LIGHT_BASE_FILENAME = '{}.csv'
TIME_COLUMN = 'time'
VALUE_COLUMN = 'value'
ANOMALY_COLUMN = 'is_anomaly'
DERIVATIVE_X = 'x_p'
DERIVATIVE_Y = 'y_p'

